# Generated by Django 2.0.7 on 2021-02-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210215_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
