# Generated by Django 2.1.5 on 2021-02-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210215_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Featured',
            field=models.BooleanField(default=False),
        ),
    ]
