# Generated by Django 2.1.5 on 2021-02-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210215_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Featured',
            new_name='featured',
        ),
    ]
